public/index.php

- [Bug] hot fix remove gkc_code
- None
-

hot fix remove gkc_code

---

app/Eloquent/Book.php
app/Eloquent/User.php
database/migrations/2020_02_17_133859_create_favorites_table.php

- [Feature]
Create tables favorites
- None
https://dev.sun-asterisk.com/issues/437403
-

model and migration

---

app/Eloquent/Book.php
app/Eloquent/User.php

 fix model user

---

resources/assets/user/css/style.css
resources/views/book/book_detail.blade.php

- [Bug]
- None
https://dev.sun-asterisk.com/issues/441534

fix book tooltip

---

resources/assets/user/css/custom.css
resources/views/book/book_detail.blade.php

fix style for book image

---

app/Providers/AppServiceProvider.php

fix mysql with laravel version 5.4

---

resources/views/user/profile.blade.php

- [Bug] Fix profile UI
- None
- 
Stg: ![stg](https://user-images.githubusercontent.com/51468316/75307457-572e5800-587e-11ea-9455-1fbb53518c51.gif)
Fixed: ![local](https://user-images.githubusercontent.com/51468316/75307459-5990b200-587e-11ea-82ce-85fa8649cb0f.gif)

 fix tab profile

---

routes/web.php

- [Bug] Can't view statisticBook
- None
-

fix view statisticBook

---

resources/views/book/book_detail.blade.php

fix related book list

---

app/Http/Controllers/CategoryController.php
resources/assets/admin/js/category.js
resources/lang/en/admin.php
resources/lang/vi/admin.php
resources/views/admin/book/list.blade.php
resources/views/admin/category/list.blade.php
resources/views/admin/layout/notification.blade.php
resources/views/admin/layout/sidebar.blade.php
routes/web.php

- [Feature] 
- None
https://dev.sun-asterisk.com/issues/444303

crud category admin

---

app/Http/Controllers/OfficeController.php
app/Repositories/Contracts/OfficeRepository.php
app/Repositories/Eloquents/OfficeEloquentRepository.php
resources/assets/admin/js/offices.js
resources/lang/en/admin.php
resources/lang/vi/admin.php
resources/views/admin/layout/sidebar.blade.php
resources/views/admin/offices/list.blade.php
routes/web.php

- [Feature]
https://dev.sun-asterisk.com/issues/444321

done list offices

---

resources/views/book/book_detail.blade.php

fix book borrowing modal

---

app/Http/Controllers/User/BookController.php
app/Repositories/Eloquents/BookCategoryEloquentRepository.php
resources/views/book/add.blade.php

fix book create validate

---

README.md
bower.json
database/seeds/OptionTableSeeder.php
package-lock.json
package.json
readme.md
resources/lang/en/page.php
resources/lang/vi/page.php
resources/views/admin/error/error.blade.php
resources/views/book/book_detail.blade.php
resources/views/layout/app.blade.php

convert Fbook to Sbook

---

app/Http/Controllers/User/BookController.php
resources/assets/user/js/main.js
resources/views/book/book_detail.blade.php
resources/views/book/books.blade.php
resources/views/index.blade.php
resources/views/layout/app.blade.php
resources/views/layout/section/latest_book.blade.php
resources/views/layout/section/modal.blade.php
resources/views/layout/section/profile_books.blade.php
resources/views/layout/section/sharing_books.blade.php
resources/views/layout/section/top_book.blade.php
routes/web.php

- [Bug] Reduce include modal
- None
-

fix view modal

---

app/Repositories/Eloquents/BookEloquentRepository.php

- [Bug] Change data from Cache to Get data from DB
- None
https://dev.sun-asterisk.com/issues/449766?issue_count=98&issue_position=10&next_issue_id=444657&prev_issue_id=449769
-

 change get cate from cache to db

---

app/Http/Controllers/User/UserController.php
app/Repositories/Eloquents/OptionEloquentRepository.php
resources/assets/user/css/custom.css
resources/assets/user/css/style.css
resources/assets/user/js/main.js
resources/assets/user/js/setting.js
resources/lang/en/page.php
resources/lang/vi/page.php
resources/views/book/book_detail.blade.php
resources/views/layout/app.blade.php
resources/views/layout/header.blade.php
resources/views/layout/section/setting_phone.blade.php
routes/web.php

- [Bug]
https://dev.sun-asterisk.com/issues/450018

convert Framgia->SunAsterisk and fix bugs in user setting

---

app/Http/Kernel.php
app/Http/Middleware/Authenticate.php
resources/assets/user/css/style.css
resources/lang/en/auth.php
resources/lang/vi/auth.php
resources/views/auth/layouts/app.blade.php
resources/views/book/book_detail.blade.php
resources/views/layout/header.blade.php

fix_redirect_login_route

---

app/Helpers/helpers.php
resources/views/layout/section/latest_book.blade.php
resources/views/layout/section/offcie_book.blade.php
resources/views/layout/section/sharing_books.blade.php
resources/views/layout/section/top_book.blade.php

fix show media book

---

resources/assets/user/css/style.css
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/layout/header.blade.php
resources/views/layout/slider.blade.php

 fix UI home

---

resources/views/book/book_detail.blade.php
resources/views/index.blade.php

- None
- 
Modal book đang lấy book hiện tại

hide register email form

---

app/Http/Controllers/User/ReviewBookController.php
app/Repositories/Eloquents/ReviewBookEloquentRepository.php
config/view.php
resources/lang/en/page.php
resources/lang/vi/page.php
resources/views/book/review.blade.php
resources/views/book/show_review.blade.php
resources/views/layout/app.blade.php
resources/views/layout/style.blade.php

- [Bug] [Feedback form] "FBOOK" words are NOT be changed to "S* BOOK"
- None
https://dev.sun-asterisk.com/issues/451173
-

change link feedback sbook

---

resources/assets/user/css/style.css
resources/assets/user/js/main.js
resources/views/index.blade.php
resources/views/layout/section/offcie_book.blade.php
resources/views/user/profile.blade.php

Fix item book office and UI profile

---

app/Eloquent/Notification.php
app/Http/Controllers/User/BookController.php
database/migrations/2020_03_03_090304_add_cover_to_users_table.php
resources/views/layout/section/notifications.blade.php

- [Bug] Fix notification not show review urself
- None
-

fix notification

---

database/migrations/2020_03_03_090304_add_cover_to_users_table.php

 migration cover

---

app/Http/Controllers/User/BookController.php
app/Providers/ComposerServiceProvider.php
config/view.php
resources/assets/user/css/cover.css
resources/assets/user/css/style.css
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/book/add.blade.php
resources/views/index.blade.php
resources/views/layout/app.blade.php
resources/views/layout/section/modal_book_preview.blade.php
resources/views/user/profile.blade.php
routes/web.php

- [Bug] Fix UI profile and suggest book when alreay in system
- None
-

fix same book create

---

app/Repositories/Eloquents/BookEloquentRepository.php
app/Repositories/Eloquents/OfficeEloquentRepository.php
resources/assets/user/css/style.css
resources/views/book/add.blade.php
resources/views/book/books.blade.php

 fix show book by office

---

app/Eloquent/Notification.php
app/Http/Controllers/User/UserController.php
app/Http/Requests/BookRequest.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
resources/assets/user/css/style.css
resources/views/book/add.blade.php
routes/web.php

- [Bug] Fix notification 
- Fix validate length author
- None
-

 fix notification

---

app/Http/Controllers/HomeController.php
app/Traits/FullTextSearch.php
resources/assets/user/css/style.css
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/layout/section/phone.blade.php
resources/views/user/profile.blade.php

- [Bug] Fix modal phone
- Fix Search
- None
-

 fix modal phone and search

---

resources/views/layout/section/phone.blade.php

modal show when don't login

---

app/Eloquent/BookUser.php
app/Helpers/helpers.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
config/view.php
resources/assets/user/css/custom.css
resources/assets/user/css/style.css
resources/assets/user/js/book_detail.js
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/book/book_detail.blade.php
resources/views/layout/section/user_list.blade.php
resources/views/user/profile.blade.php

- [Feature] Edit book detail 
- None
-

 edit book detail page

---

app/Helpers/helpers.php
app/Http/Controllers/Auth/LoginController.php
app/Http/Requests/Admin/BookRequest.php
app/Http/Requests/BookRequest.php
app/Repositories/Eloquents/BookUserEloquentRepository.php

- [Bug] Fix not display request and empty address
- None
-

fix request not display

---

app/Helpers/helpers.php
app/Http/Controllers/HomeController.php
resources/assets/user/css/search-page.css
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/layout/header.blade.php
resources/views/layout/section/modal.blade.php
resources/views/search.blade.php
webpack.mix.js

- [Bug] Search page and add message when borrow book
- Fix address when null -> errow when show address office
- Fix count reviews in popup detail
- None
https://edu-redmine.sun-asterisk.vn/issues/22153
https://edu-redmine.sun-asterisk.vn/issues/22151
https://edu-redmine.sun-asterisk.vn/issues/22174
-

 fix search page and add message when cancel and borrow book

---

app/Http/Controllers/OfficeController.php
resources/assets/admin/js/books.js
resources/assets/admin/js/offices.js
resources/assets/admin/js/user.js
resources/assets/user/css/custom.css
resources/assets/user/js/book_detail.js
resources/assets/user/js/main.js
resources/lang/en/page.php
resources/lang/vi/page.php
resources/views/admin/book/list.blade.php
resources/views/admin/offices/list.blade.php
resources/views/admin/user/list.blade.php
resources/views/book/add.blade.php
resources/views/book/book_detail.blade.php

Fix action borrow

---

resources/assets/user/js/main.js

 fix UI admin

---

app/Http/Controllers/User/NotificationController.php
config/view.php
resources/assets/admin/js/uploadFile.js
resources/assets/user/css/custom.css
resources/assets/user/js/main.js
resources/views/layout/section/modal.blade.php

- None
https://edu-redmine.sun-asterisk.vn/issues/22322
-

 add loadmore

---

app/Http/Controllers/User/BookController.php
app/Http/Controllers/User/UserController.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/book/book_detail.blade.php

- [Task] cant remove onwer when any read or return
- None
https://edu-redmine.sun-asterisk.vn/issues/22304
-

cant remove onwer when any read or return

---

resources/assets/user/css/custom.css
resources/views/layout/section/search.blade.php

 fix UI tab

---

app/Eloquent/BookUser.php
app/Eloquent/User.php
app/Helpers/helpers.php
app/Http/Controllers/User/BookController.php
app/Http/Controllers/User/MyRequestController.php
app/Providers/AppServiceProvider.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
app/Repositories/Eloquents/NotificationEloquentRepository.php
app/Repositories/Eloquents/UserEloquentRepository.php
config/model.php
config/view.php
database/migrations/2020_03_13_234447_add_expire_to_book_user.php
resources/assets/user/css/custom.css
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/layout/app.blade.php
resources/views/user/my_request.blade.php
routes/web.php

-[Feature] -> Book about to expire ( < 1day) will has popup notification 
- Expire ( boolean ) -> true will show modal list book about to expire and reverse
- User can choose extend or not extend
- If choose extend then will send request to owner ( update expire = false ) 
- If choose not extend  then update expire = false 
- Owner accept then update days to read and if cancel then delete request expire
- If user request expire and return book then delete request expire
- None

extend for book

---

app/Helpers/helpers.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
database/migrations/2020_03_25_212631_add_day_return_to_book_user.php
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/user/my_request.blade.php

- [Bug] Fix date return invalid
- None
https://edu-redmine.sun-asterisk.vn/issues/22436
-

 Fix date return

---

app/Http/Controllers/User/BookController.php
app/Http/Controllers/User/UserController.php
app/Repositories/Eloquents/NotificationEloquentRepository.php

 send_notification_to_followers

---

app/Helpers/helpers.php
resources/assets/user/css/custom.css
resources/lang/en/settings.php
resources/views/book/book_detail.blade.php
resources/views/book/books.blade.php
resources/views/user/my_request.blade.php

- [Feature] Fix UI myrequest page
- None
https://edu-redmine.sun-asterisk.vn/issues/22324
https://edu-redmine.sun-asterisk.vn/issues/22337
-

 fix UI my request

---

app/Http/Controllers/User/VoteController.php
app/Repositories/Eloquents/VoteEloquentRepository.php
resources/assets/user/css/custom.css
resources/assets/user/js/vote.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/book/book_detail.blade.php
resources/views/book/show_review.blade.php
webpack.mix.js

- [Feature] User có thể xem và vote review ngay tại tab Review
- None
https://edu-redmine.sun-asterisk.vn/issues/22252
-

 support_tab_book_detail

---

app/Http/Controllers/User/BookController.php

 fix sendNotificationToFollowers

---

app/Helpers/helpers.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
resources/assets/user/js/main.js
resources/lang/vi/settings.php
resources/views/layout/app.blade.php

- [Bug] Vẫn hiển thị button "Mượn sách" cho người mượn khi gia hạn sách thành công/thất bại
- None
https://edu-redmine.sun-asterisk.vn/issues/22577
-

Fix expire book

---

app/Helpers/helpers.php
resources/assets/user/css/custom.css
resources/views/book/books.blade.php

 fix not display data

---

app/Helpers/helpers.php
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/layout/app.blade.php
resources/views/user/my_request.blade.php

- Thêm status "Expired" khi sách đã hết hạn mà chưa trả sách
- None
https://edu-redmine.sun-asterisk.vn/issues/22438
-

   add status expired

---

app/Helpers/helpers.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
composer.json
database/migrations/2020_04_02_113938_change_type_date_return_book_user.php
resources/views/user/my_request.blade.php

 fix display expired

---

app/Eloquent/BookUser.php
app/Helpers/helpers.php
app/Http/Controllers/User/MyRequestController.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
config/view.php
resources/assets/user/css/custom.css
resources/assets/user/js/main.js
resources/assets/user/js/my_request.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/user/my_request.blade.php
resources/views/user/requests.blade.php

-  Thêm filter status cho các request
- None
https://edu-redmine.sun-asterisk.vn/issues/22269
-

Add filter my request

---

resources/views/auth/layouts/app.blade.php

fix js error

---

resources/views/auth/layouts/app.blade.php

Reverts framgia/sbook_rebuild#83

Revert "fix js error"

---

app/Eloquent/BookUser.php
app/Helpers/helpers.php
app/Http/Controllers/User/UserController.php
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/book/book_detail.blade.php

- None
https://edu-redmine.sun-asterisk.vn/issues/22664
-

[BUG][22664][Book detail] Vẫn có thể mượn sách trong khi sách đang chờ trả bởi người khác

---

app/Eloquent/BookUser.php
resources/views/book/book_detail.blade.php

 fix bug crash app

---

app/Http/Controllers/User/UserController.php
app/Http/Requests/BookRequest.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
resources/lang/en/validation.php
resources/lang/vi/validation.php

- None
https://edu-redmine.sun-asterisk.vn/issues/22577
-

[BUG][22577][Gia hạn sách] [Book detai] Vẫn hiển thị button "Mượn sách" cho người mượn khi gia hạn sách thành công/thất bại

---

app/Http/Controllers/User/MyRequestController.php
app/Providers/AppServiceProvider.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
app/Repositories/Eloquents/NotificationEloquentRepository.php
resources/assets/user/css/custom.css
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/layout/section/notifications.blade.php
resources/views/user/notifications.blade.php

- [Notification] Gửi thông báo cho [Người chờ mượn] nếu Owner đã cho người khác mượn sách
- None
-

[SUPPORT][22745][Notification] Gửi thông báo cho [Người chờ mượn] nếu Owner đã cho người khác mượn sách

---

app/Helpers/helpers.php
app/Repositories/Eloquents/NotificationEloquentRepository.php
resources/assets/admin/js/uploadFile.js
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/vi/settings.php
resources/views/book/book_detail.blade.php

[BUG][22745-22718]

---

app/Repositories/Eloquents/BookUserEloquentRepository.php
resources/assets/admin/js/uploadFile.js
resources/assets/user/css/custom.css
resources/lang/en/validation.php
resources/lang/vi/validation.php
resources/views/layout/section/modal.blade.php

 fix UI and display button share book

---

app/Helpers/helpers.php
resources/views/book/books.blade.php
resources/views/book/review.blade.php
resources/views/book/show_review.blade.php
resources/views/layout/section/modal.blade.php
resources/views/layout/section/modal_book_preview.blade.php
resources/views/layout/section/profile_books.blade.php

fix image book default

---

app/Http/Requests/UploadCoverRequest.php
app/Repositories/Eloquents/BookUserEloquentRepository.php
app/Repositories/Eloquents/NotificationEloquentRepository.php
resources/assets/admin/js/uploadFile.js
resources/assets/user/js/main.js
resources/lang/en/validation.php
resources/lang/vi/validation.php
resources/views/user/profile.blade.php

- None
https://edu-redmine.sun-asterisk.vn/issues/22969
https://edu-redmine.sun-asterisk.vn/issues/22966
https://edu-redmine.sun-asterisk.vn/issues/22964
-

[BUG][22964][22969][22966] Fix bug notification

---

app/Repositories/Eloquents/NotificationEloquentRepository.php
resources/assets/admin/js/uploadFile.js
resources/assets/user/js/main.js
resources/lang/en/settings.php
resources/lang/en/validation.php
resources/lang/vi/validation.php

change notification

---

.rocketeer/config.php
.rocketeer/hooks.php
.rocketeer/paths.php
.rocketeer/remote.php
.rocketeer/scm.php
.rocketeer/stages.php
.rocketeer/strategies.php
framgia-ci.yml

setup auto deploy for project

---

.rocketeer/scm.php

change scm file
